repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
    args: ["-l 100"]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    args: ["--ignore=E231, W503, E722, E231", "--max-line-length=100"]
- repo: https://github.com/timothycrosley/isort
  rev: 5.7.0
  hooks: 
  - id: isort
